# Generated by Django 4.2.1 on 2023-06-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=150)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
